function [ sacdat_lp, sachd_lp ] = lowpassSAC( sachd, sacdat, filter_lp )
%LOWPASSSAC low-pass filters sac data using a given lowpass filter
%--------------------------------------------------------------------------
% Usage: [ sachd_lp, sacdat_lp ] = lowpassSAC( sachd,sacdat, filter_lp )
%--------------------------------------------------------------------------
% Inputs:
%   sachd: sac head structure (read by irdsac or created by inewsachd)
%   sacdat: sac data array
%   (see the matlab help of fdesign.lowpass for the following parameters)
%   filter_lp: filter structure generated by fdesign.lowpass and design
%--------------------------------------------------------------------------
% Outputs:
%   sachd_lp: sac head structure
%   sacdat_lp: sac data array after lowpass filtered
%--------------------------------------------------------------------------
% created on Oct. 15, 2011
%--------------------------------------------------------------------------
% note:
%   1) to desing a lowpass filter:
%   % Fpass = 2;
    % Fstop = 4;
    % Apass = 1;
    % Astop = 60;
    % Fs = 1/hd.delta;
    % %
    % filter_para = fdesign.lowpass(Fpass,Fstop,Apass,Astop,Fs);
    % % design filter
    % filter_lp = design(filter_para,'equiripple');
    % % lowpass 
    % [ dat_lp, hd_lp ] = lowpassSAC( hd, dat, filter_lp );

%%
%--------------------------------------------------------------------------
% filter
%--------------------------------------------------------------------------
dt = sachd.delta;
%
grpdelay = dt*(filter_lp.impzlength-1)/2;
%--------------------------------------------------------------------------
% filtering data
%--------------------------------------------------------------------------
sacdat_lp = filter(filter_lp.numerator,1,sacdat);
sachd_lp = sachd;
sachd_lp.b = sachd.b-grpdelay;
sachd_lp.e = sachd.e-grpdelay;
sachd_lp.npts = length(sacdat_lp);
end
